suppressPackageStartupMessages({library(data.table); library(yaml); library(digest)})
source("R/assert.R")
source("R/config.R")
source("R/join_assertions.R")
source("R/input_manifest.R")
source("R/ebird_ingestion.R")
source("R/herring_event_engineering.R")
source("R/metadata_audit.R")

checksum <- identical(tolower(Sys.getenv("HERRING_EBIRD_V2_VERIFY_INPUT_SHA256", "false")), "true")
audit <- run_input_metadata_audit(read_project_config(), checksum = checksum)
write_input_audit(audit)
cat("Input sizes, bundle completeness, and required headers passed; checksum mode: ", checksum, ".\n", sep = "")
