suppressPackageStartupMessages({library(data.table); library(yaml)})
source("R/assert.R")
source("R/species_registry.R")
source("R/model_registry.R")
species <- read_species_registry()
guilds <- read_guild_registry()
validate_species_guilds(species, guilds)
models <- read_model_registry()
cat(nrow(species), " species registry rows; ", nrow(guilds), " guilds; ", nrow(models), " models.\n", sep = "")
