suppressPackageStartupMessages(library(data.table))
source("R/assert.R")
source("R/species_registry.R")
source("R/model_registry.R")
counts <- validate_registry_bundle()
cat(paste(names(counts), unlist(counts), sep = "=", collapse = "; "), "\n")
