suppressPackageStartupMessages({library(data.table); library(yaml); library(jsonlite)})
source("R/assert.R")
source("R/config.R")
source("R/metadata_audit.R")
cfg <- read_project_config()
paths <- resolve_input_paths(cfg)
dir.create("outputs/metadata", recursive = TRUE, showWarnings = FALSE)

sed <- profile_sed_metadata(paths[["ebird_sed"]])
fwrite(sed$protocol, "outputs/metadata/sed_protocol_counts.csv")
fwrite(sed$completeness, "outputs/metadata/sed_complete_counts.csv")
fwrite(sed$effort_missingness, "outputs/metadata/sed_effort_missingness.csv")

herring <- profile_herring_metadata(paths[["herring_csv"]])
fwrite(herring$field_summary, "outputs/metadata/herring_field_summary.csv")
fwrite(herring$method, "outputs/metadata/herring_method_counts.csv")
fwrite(herring$component_pattern, "outputs/metadata/herring_component_patterns.csv")
cat("Source metadata profiles written. No bird-response outcome was modeled.\n")
